package com.bank.account;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.bank.account.Account;
import com.bank.account.AccountRepository;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/accountsummary") // This means URL's start with /accountsummary (after Application path)
@CrossOrigin
public class AccountSummaryController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private AccountRepository accountRepository;
	
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Account> getAllUsers() {
		// This returns a JSON or XML with the users
		return accountRepository.findAll();
	}
	
	@GetMapping(path="/all/{id}")
	public @ResponseBody Account getTeam(@PathVariable Long id){
		System.out.println("1111111111");
		return accountRepository.findOne(id);
	}
}
